import {
    isObject
} from 'lodash';
import AppForm from '../app-components/Form/AppForm';
import {
    GetCommentQueue,
} from '../event-bus/app-events';

Vue.component('examination-form', {
    mixins: [AppForm],
    props: [
        'services',
        'statusAddEdit'
    ],
    data: function () {
        return {
            lab_detail: [],
            service: [],
            info: {
                chief_complaint: '',
                present_history_of_illness: '',
                heent: '',
                neck: '',
                pulmonary_system: '',
                cardiovascular_system: '',
                gastrointestinal_system: '',
                urinary_system: '',
                muscle_skeleton: '',
                endocrine_system: '',
                nervous_system: '',
                family_history: '',
                social_history: '',
                htn: '',
                dm: '',
                type: '',
                cardiovascular_disease: '',
                kidney_disease: '',
                hematologic_disease: '',
                tb: '',
                hbv: '',
                hcv: '',
                cancer: '',
                conscious: '',
                active_position: '',
                passive_position: '',
                coma: '',
                development_normal: '',
                development_gigantism: '',
                development_pituitary: '',
                development_dwarfism: '',
                development_cretinism: '',
                nutrition_normal: '',
                nutrition_obesity: '',
                nutrition_emaciation: '',
                nutrition_cachexia: '',
                bp: '',
                hr: '',
                pr: '',
                Spo2: '',
                t: '',
                w: '',
                bmi: '',
                thyroid_gland: '',
                skin: '',
                lymph_node: '',
                respiratory_system_inspection: '',
                repiratory_rhythm_regular: '',
                repiratory_rhythm_tachypnea: '',
                repiratory_rhythm_bradypnea: '',
                repiratory_rhythm_dyspnea: '',
                repiratory_rhythm_orthopnea: '',
                repiratory_rhythm_positive_three_depressions_sign: '',
                repiratory_rhythm_caynosis: '',
                repiratory_rhythm_asymmetric_chest: '',
                repiratory_rhythm_flat_chest: '',
                repiratory_rhythm_barrel_chest: '',
                repiratory_rhythm_furnnel_chest: '',
                repiratory_rhythm_pigeon_chest: '',
                repiratory_rhythm_subcutanous_emphysema: '',
                respiratory_system_palpation: '',
                describe_abnormality_decrease: '',
                describe_abnormality_in_crease: '',
                describe_abnormality_left_sight: '',
                describe_abnormality_right_sight: '',
                vocal_fremitus_decrease: '',
                vocal_fremitus_in_crease: '',
                vocal_fremitus_left_sight: '',
                vocal_fremitus_right_sight: '',
                pleural_friction_fremitus_positive: '',
                pleural_friction_fremitus_negative: '',
                pleural_friction_fremitus_left_sight: '',
                pleural_friction_fremitus_right_sight: '',
                respiratory_system_percussion: '',
                dullness_left_sight: '',
                dullness_right_sight: '',
                tympany_left_sight: '',
                tympany_right_sight: '',
                hyperresonance_left_sight: '',
                hyperresonance_right_sight: '',
                respiratory_system_auscultation: '',
                breath_sound_decrease: '',
                breath_sound_in_crease: '',
                breath_sound_left_sight: '',
                breath_sound_right_sight: '',
                crepitation_coarse: '',
                crepitation_medium: '',
                crepitation_fine: '',
                crepitation_crepitus: '',
                crepitation_left_sight: '',
                crepitation_right_sight: '',
                wheeze_sibilant: '',
                wheeze_sonorous: '',
                wheeze_right_sight: '',
                wheeze_left_sight: '',
                pleural_friction_rub_positive: '',
                pleural_friction_rub_negative: '',
                pleural_friction_rub_right_sight: '',
                pleural_friction_rub_left_sight: '',
                cardiovascular_system_inspection: '',
                clubbing_finger: '',
                positive_jugular_vein_distention: '',
                apical_impulse_at: '',
                cardiovascular_system_palpation: '',
                mitral_area: '',
                aortic_area: '',
                tricuspid_area: '',
                pulmonary_area: '',
                left_ventricular_heave: '',
                right_ventricular_heave: '',
                pericardial_friction_fremitus: '',
                cardiovascular_system_percussion: '',
                left_sight_enlargement: '',
                right_sight_enlargement: '',
                cardiovascular_system_auscultation: '',
                tachycardia: '',
                bradycardia: '',
                regular: '',
                arrhythmia: '',
                S1_decrease: '',
                S2_decrease: '',
                S1_increase: '',
                S2_increase: '',
                S1_splitting: '',
                S2_splitting: '',
                general_splitting: '',
                fixed_splitting: '',
                paradoxical_splitting: '',
                gallop_rhythm: '',
                protodiastolic_gallop: '',
                late_diastolic_gallop: '',
                summation_gallop: '',
                opening_snap: '',
                pericardial_knock: '',
                tumor_plop: '',
                click: '',
                systolic: '',
                diastolic: '',
                continuous: '',
                crescendo: '',
                decrescendo: '',
                plateau: '',
                pericardial_friction_sound_positive: '',
                pericardial_friction_sound_negative: '',
                pericardial_friction_sound_continuous: '',
                pericardial_friction_sound_crescendo: '',
                pericardial_friction_sound_decrescendo: '',
                pericardial_friction_sound_plateau: '',
                gastrointestinal_system_inspection: '',
                gastrointestinal_system_palpation: '',
                ruq: '',
                rlq: '',
                luq: '',
                llq: '',
                rebound_tenderness: '',
                positive_peritoneal_irritation_sign: '',
                positive_murphy_sign: '',
                gastrointestinal_auscultation: '',
                abdominal_distension: '',
                abdominal_concavity: '',
                spider_nevi: '',
                caput_medusa: '',
                palmar_erythema: '',
                duputrens_contracture: '',
                leukonychia: '',
                gastral_pattern: '',
                intestinal_pattern: '',
                peristalsis: '',
                gastrointestinal_percussion: '',
                resonance: '',
                dullness: '',
                hyperresonance: '',
                positive_fluid_thrill: '',
                shifting_dullness: '',
                positive_peritoneal_irritation: '',
                positive_murphy_sign: '',
                cardiovascular_system_auscultation: '',
                bowel_sound_increase: '',
                bowel_sound_decrease: '',
                bowel_sound_decrease_positive_abdominal_aortic_bruits: '',
                urinary_system_inspection: '',
                urinary_system_palpation: '',
                urinary_system_percussion: '',
                urinary_system_auscultation: '',
                urinary_system_skeleton: '',
                urinary_system_nervous_system: '',
                glasgow_coma_score: '',
                olfactory_nerve: '',
                optic_nerve: '',
                trigeminal_nerve: '',
                facial_nerve: '',
                vestibulocochlear_nerve: '',
                glossopharyngeal_nerve: '',
                vagal_nerve: '',
                accessory_nerve: '',
                hypoglossal_nerve: '',
                muscle_bulk: '',
                muscular_tension: '',
                muscle_strength: '',
                finger_nose_test_negative: '',
                finger_nose_test_positive: '',
                heel_to_shin_test_negative: '',
                heel_to_shin_test_positive: '',
                rapid_alternating_movement_negative: '',
                rapid_alternating_movement_positive: '',
                tandem_walking_negative: '',
                tandem_walking_positive: '',
                romberg_test_negative: '',
                romberg_test_positive: '',
                pain_increase: '',
                pain_decrease: '',
                light_touch: '',
                position_test: '',
                point_localization: '',
                temperature: '',
                vibration: '',
                two_point_discrimination: '',
                stereognosis_test: '',
                babinski_sign_negative: '',
                babinski_sign_positive: '',
                oppenheim_sign_negative: '',
                oppenheim_sign_positive: '',
                chaddock_sign_negative: '',
                chaddock_sign_positive: '',
                hoffmann_sign_negative: '',
                hoffmann_sign_positive: '',
                kerning_sign_negative: '',
                kerning_sign_positive: '',
                brudzinski_sign_negative: '',
                brudzinski_sign_positive: '',
                stiff_neck_negative: '',
                stiff_neck_positive: '',
                comment: ''
            },
            index: 0,
            printExam: null,
        }
    },
    created() {
        this.$eventBus.publish(new GetCommentQueue(this.form));

        this.lab_detail = this.form.patient_history_last.examination_services_edit

        if (this.form.patient_history_last.infor_History_key_value.length != 0) {
            this.info = this.form.patient_history_last.infor_History_key_value
        } else {
            this.info = {}
        }


    },
    beforeDestory() {},
    methods: {
        // onPrint() {
        //     var _this = this;
        //     var timestamp = Date.now();
        //     _this.printExam = '/admin/print-examination?' + timestamp;

        // },
        onSave() {
            var _this = this;
            var data = {
                'patient_id': _this.form.patient_id,
                'lab_detail': _this.lab_detail,
                'service_id': _this.service,
                'queue_id': _this.form.id,
                'employee_id': _this.form.employee_id,
                'info': _this.info,
                'status_add_edit': _this.statusAddEdit,
            };


            axios.post(_this.action, data).then(function (response) {
                return _this.onSuccess(response.data);
            }).catch(function (errors) {
                return _this.onFail(errors.response.data);
            });
        },
        checkAll(serviceId) {
            this.unCheckAll(serviceId);

            var service = _.find(this.services, function (o) {
                return o.id == serviceId;
            });

            var labDetailService = service.lab_detail_service.map((n) => {
                return {
                    lab_detail_id: n.id,
                    service_id: serviceId,
                    lab_id: n.lab_id
                };
            });

            this.lab_detail = this.lab_detail.concat(labDetailService);
        },
        unCheckAll(serviceId) {
            this.lab_detail = this.lab_detail.filter(i => i.service_id != serviceId);
        },
    }
});
